import Foundation

/// Production adapters must use a fixed interface and a root-owned, durable journal.
/// Writing the restoration obligation must reach stable storage before lowering AWDL.
public protocol AWDLSystem {
    func isUp() throws -> Bool
    func setUp(_ up: Bool) throws
    func restorationPending() throws -> Bool
    func writeRestorationPending(_ pending: Bool) throws
}

/// A single serialized executor must own this controller and its system adapter.
/// Client authentication and active-session consent belong at the XPC boundary.
/// Owners are generated by the helper for authenticated connections, never supplied
/// by a remote peer. Connection invalidation calls disconnect; a timer calls tick.
public final class LeaseController {
    public enum Failure: Error, Equatable {
        case unknownLease, capacity, invalidClock, optimizationLost
    }

    private struct Lease {
        let owner: UUID
        var expires: TimeInterval
    }

    public static let leaseDuration: TimeInterval = 10
    public static let maximumLeases = 128
    private let system: AWDLSystem
    private let clock: () -> TimeInterval
    private var leases: [UUID: Lease] = [:]
    private var restorePending: Bool
    private var lastTime: TimeInterval = 0

    /// Startup restores interrupted work before accepting any new requests.
    /// Failed recovery throws: the service must stay unavailable and retry recovery.
    public init(system: AWDLSystem, clock: @escaping () -> TimeInterval) throws {
        self.system = system
        self.clock = clock
        self.restorePending = try system.restorationPending()
        try restoreIfIdle()
    }

    public var activeLeaseCount: Int { leases.count }
    public var needsRestoration: Bool { restorePending }

    private func now() throws -> TimeInterval {
        let value = clock()
        guard value.isFinite, value >= lastTime else { throw Failure.invalidClock }
        lastTime = value
        return value
    }

    private func expire(at time: TimeInterval) throws {
        leases = leases.filter { $0.value.expires > time }
        try restoreIfIdle()
    }

    private func restoreIfIdle() throws {
        guard leases.isEmpty, restorePending else { return }
        try system.setUp(true)
        // Retain the obligation if clearing the durable journal fails.
        try system.writeRestorationPending(false)
        restorePending = false
    }

    public func begin(owner: UUID) throws -> UUID {
        let time = try now()
        try expire(at: time)
        guard leases.count < Self.maximumLeases else { throw Failure.capacity }
        if leases.isEmpty, try system.isUp() {
            // If the write reports an ambiguous failure, retain an in-memory
            // obligation as well. No lowering is attempted before write success.
            restorePending = true
            try system.writeRestorationPending(true)
            do {
                try system.setUp(false)
            } catch {
                // Lowering can fail after taking effect. Keep durable recovery
                // information until restoration actually succeeds.
                try? restoreIfIdle()
                throw error
            }
        }
        guard try !system.isUp() else { throw Failure.optimizationLost }
        let id = UUID()
        leases[id] = Lease(owner: owner, expires: time + Self.leaseDuration)
        return id
    }

    public func renew(_ id: UUID, owner: UUID) throws {
        let time = try now()
        try expire(at: time)
        guard let lease = leases[id], lease.owner == owner else {
            throw Failure.unknownLease
        }
        guard try !system.isUp() else { throw Failure.optimizationLost }
        leases[id]?.expires = time + Self.leaseDuration
    }

    public func end(_ id: UUID, owner: UUID) throws {
        try expire(at: now())
        guard let lease = leases[id], lease.owner == owner else {
            throw Failure.unknownLease
        }
        leases.removeValue(forKey: id)
        try restoreIfIdle()
    }

    public func disconnect(owner: UUID) throws {
        leases = leases.filter { $0.value.owner != owner }
        try expire(at: now())
    }

    /// Call at least once per second, including while no leases remain: failed
    /// restoration is retried. Use a monotonic clock that advances during sleep.
    public func tick() throws {
        try expire(at: now())
    }

    public func shutdown() throws {
        leases.removeAll()
        try restoreIfIdle()
    }
}
