/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as EmailRouteImport } from './routes/email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DesktopConnectRouteImport } from './routes/desktop.connect'
import { Route as DesktopConnectedRouteImport } from './routes/desktop.connected'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopConnectRoute = DesktopConnectRouteImport.update({
  id: '/desktop/connect',
  path: '/desktop/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopConnectedRoute = DesktopConnectedRouteImport.update({
  id: '/desktop/connected',
  path: '/desktop/connected',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email': typeof EmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/desktop/connected': typeof DesktopConnectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email': typeof EmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/desktop/connected': typeof DesktopConnectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email': typeof EmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/desktop/connect': typeof DesktopConnectRoute
  '/desktop/connected': typeof DesktopConnectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/desktop/connect'
    | '/desktop/connected'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/desktop/connect'
    | '/desktop/connected'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/desktop/connect'
    | '/desktop/connected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EmailRoute: typeof EmailRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  DesktopConnectRoute: typeof DesktopConnectRoute
  DesktopConnectedRoute: typeof DesktopConnectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/connect': {
      id: '/desktop/connect'
      path: '/desktop/connect'
      fullPath: '/desktop/connect'
      preLoaderRoute: typeof DesktopConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/connected': {
      id: '/desktop/connected'
      path: '/desktop/connected'
      fullPath: '/desktop/connected'
      preLoaderRoute: typeof DesktopConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EmailRoute: EmailRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  DesktopConnectRoute: DesktopConnectRoute,
  DesktopConnectedRoute: DesktopConnectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
